name: CI/CD pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Configurar Node.js
        uses: actions/checkout@v2
        with:
          node-version: '14'

      - name: instalar Dependências
        run: npm install

      - name: Rodar testes
        run: npm test

      - name: Build do projeto
        run: npm run build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do Código
        uses: actions/checkout@v2

      - name: Deploy para Servidor
        env:
          FTP_SERVER: ${{ secrets.FTP_SERVER}}
          FTP_USERNAME: ${{ secrets.FTP_USERNAME}}
          DTP_PASSWORD: ${{ secrets.FTP_PASSWORD}}
        run: |
          echo: "fazendo upload dos arquivos"

      
      
        
